### ISSUE TITLE
Not totally automatically?

### ISSUE THREAD

**Issue by jiamo** [grumpy-systems/debian-iso#1]
When boot from the generated iso. It will paused at UserName Input.

After I modify the preseed.cfg , added such 3 lines:

```
d-i passwd/username string debian
d-i passwd/user-password password debian
d-i passwd/user-password-again password debian
```
The install process still pause at Username Input.

**Comment by jiamo** [comment]
Solved by add more line

```
d-i passwd/user-fullname string debian
```

**Comment by grumpy-systems** [comment]
Sorry, this was me pushing my local copy (I don't have it fully automated) on accident.  I'll update the docs to have both options.
